# Generated by Django 5.2 on 2025-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darklit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='darklit.author', verbose_name='Authors'),
        ),
    ]
